Circleci: Updating to more recent format.
Signed-off-by: Ali Rasim Kocal <arkocal@posteo.net>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,43 +2,43 @@
 #
 # Check https://circleci.com/docs/2.0/language-python/ for more details
 #
-version: 2
-jobs:
-  build:
-    docker:
-      # specify the version you desire here
-      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
-      - image: circleci/python:3.6.1
-
-      # Specify service dependencies here if necessary
-      # CircleCI maintains a library of pre-built images
-      # documented at https://circleci.com/docs/2.0/circleci-images/
-      # - image: circleci/postgres:9.4
-
+version: 2.1
+executors:
+  vm-executor:
+    machine:
+      enabled: true
+      image: ubuntu-1604:201903-01
     working_directory: ~/repo
+    environment:
+      shell: /bin/bash
+      TERM: xterm
+      TZ: "Europe/Berlin"
+  docker-executor:
+    docker:
+      - image: circleci/node:10.0
+    working_directory: ~/repo
+    environment:
+      shell: /bin/bash
+      TERM: xterm
 
+commands:
+  install-sdk:
+    description: "Install sdk and required testing tools."
     steps:
-      - checkout
-
       - run:
-          name: Install
-          shell: /bin/bash
+          name: "Prepare Ubuntu and install SDK"
           command: |
-            sudo python setup.py install
-            sudo pip install pylint pycodestyle pydocstyle
-
+            sudo apt update || echo "update (partially) failed, probably OK to continue"
+            sudo rm -rf /opt/circleci/.pyenv && curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
+            pyenv install 3.8.5
+            pyenv local 3.8.5
+            pip install pylint pycodestyle pydocstyle setuptools
+            python setup.py install
+  check-signed:
+    description: "Check whether latest commit is signed"
+    steps:
       - run:
-          name: Run linters
-          shell: /bin/bash
-          command: |
-            pylint oisp --score=n || exit 1
-            pycodestyle oisp || exit 1
-            pycodestyle test || exit 1
-            pydocstyle oisp --add-ignore=D105 || exit 1
-
-      - run:
-          name: Check whether most recent commit is signedoff
-          shell: /bin/bash
+          name: Check whether most recent commit is signed
           command: |
             MESSAGE=`git log -1 --pretty=%B`
             echo "Checking whether signed"
@@ -48,3 +48,24 @@ jobs:
               echo "Commit is not signedoff"
               exit 1
             fi
+  lint:
+    description: "Run linters for code and comments."
+    steps:
+      - run:
+          command: |
+            pyenv local 3.8.5
+            make lint
+
+jobs:
+  e2e-test:
+    executor: vm-executor
+    steps:
+      - checkout
+      - check-signed
+      - install-sdk
+      - lint
+
+workflows:
+  workflow:
+    jobs:
+      - e2e-test
